### PR TITLE
Add css and js from bootstrap and customize index

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by ccsaposs** [comment]
@JakeRoggenbuck Can you wait for me to merge the Firebase Hosting stuff before merging this PR?

**Comment by JakeRoggenbuck** [comment]
Does the order matter?

**Comment by ccsaposs** [comment]
> Does the order matter?

Yeah, since Firebase Hosting requires files in a certain location

**Comment by JakeRoggenbuck** [comment]
> Yeah, since Firebase Hosting requires files in a certain location
Okay, sure. They need to be in `public/` right?

**Comment by ccsaposs** [comment]
Custom theming added in #15

**Pull request closed without merging**
